---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: molecule/requirements.yml

driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    # Debian Buster ami
    # image: ami-05850fe0bf797791c
    image_owner: "136693071363"
    image_name: "debian-10-amd64-*"
    instance_type: t2.micro
    vpc_subnet_id: "${AWS_MOLECULE_SUBNET}"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
verifier:
  name: testinfra
  lint:
    name: flake8
