---
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: molecule/requirements.yml

driver:
  name: docker
platforms:
  - name: homelab-local
    image: homelab:local
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: testinfra
scenario:
  # Do nother with this docker test. Normally means it will not work in docker
  create_sequence:
    - dependency
  check_sequence:
    - dependency
    - cleanup
  converge_sequence:
    - dependency
  destroy_sequence:
    - dependency
    - cleanup
  test_sequence:
    - lint
    - dependency
    - cleanup
